{
  "data": [
    {
      "tag": "pyunit test_python_software.TestSoftware.test_sum:5",
      "location": {
        "kind": "file",
        "file": "./unittests_python/test_python_software.py",
        "line": 5,
        "column": null
      },
      "name": "test_python_software.TestSoftware.test_sum:5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req vanillaEg.make_sum"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_python_software.TestSoftware.test_not_traced_function:9",
      "location": {
        "kind": "file",
        "file": "./unittests_python/test_python_software.py",
        "line": 9,
        "column": null
      },
      "name": "test_python_software.TestSoftware.test_not_traced_function:9",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_python_software2.TestSoftware2.test_int_value:5",
      "location": {
        "kind": "file",
        "file": "./unittests_python/test_python_software2.py",
        "line": 5,
        "column": null
      },
      "name": "test_python_software2.TestSoftware2.test_int_value:5",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req vanillaEg.output_value_int"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    },
    {
      "tag": "pyunit test_python_software2.TestSoftware2.test_dec_value:9",
      "location": {
        "kind": "file",
        "file": "./unittests_python/test_python_software2.py",
        "line": 9,
        "column": null
      },
      "name": "test_python_software2.TestSoftware2.test_dec_value:9",
      "messages": [],
      "just_up": [],
      "just_down": [],
      "just_global": [],
      "refs": [
        "req vanillaEg.output_value_decimal"
      ],
      "framework": "PyUnit",
      "kind": "Test",
      "status": null
    }
  ],
  "generator": "lobster_python",
  "schema": "lobster-act-trace",
  "version": 3
}

